import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { DevHubThemeProvider } from "@dev-hub/shared/theme/DevHubThemeProvider";

export const metadata: Metadata = {
  title: "Dev Hub App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <DevHubThemeProvider>
            {children}
          </DevHubThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
