import type { Metadata } from "next";
import { ThemeProvider } from "@dev-hub/shared/theme/ThemeProvider";
import { SideBarProvider } from "@dev-hub/shared/components/SideBar/SideBarContext";
import { MainLayout } from "@dev-hub/shared/layouts/MainLayout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider>
          <SideBarProvider>
            <MainLayout>{children}</MainLayout>
          </SideBarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
